---
title: "MTH020: Data Visualization"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---

### Introduction

Definitions by IBM 

> What is data visualization? Data visualization is the representation of data through use of common graphics, such as charts, plots, infographics, and even animations. These visual displays of information communicate complex data relationships and data-driven insights in a way that is easy to understand.

> Data visualization can be utilized for a variety of purposes, and it’s important to note that is not only reserved for use by data teams. Management also leverages it to convey organizational structure and hierarchy while data analysts and data scientists use it to discover and explain patterns and trends. 

### R and Rstudio 

The GNU General Public License (GNU GPL or simply GPL) is a series of widely used free software licenses that guarantee end users the four freedoms to run, study, share, and modify the software.

R is a programming language for statistical computing and graphics supported by the R Core Team and the R Foundation for Statistical Computing. Created by statisticians Ross Ihaka and Robert Gentleman, R is used among data miners, bioinformaticians and statisticians for data analysis and developing statistical software.[7] The core R language is augmented by a large number of extension packages containing reusable code and documentation. 

The official R software environment is an open-source free software environment released as part of the GNU Project and available under the GNU General Public License. It is written primarily in C, Fortran, and R itself (partially self-hosting). Precompiled executables are provided for various operating systems. R has a command line interface.[11] Multiple third-party graphical user interfaces are also available, such as RStudio, an integrated development environment, and Jupyter, a notebook interface. 

RStudio is an integrated development environment for R, a programming language for statistical computing and graphics. It is available in two formats: RStudio Desktop is a regular desktop application while RStudio Server runs on a remote server and allows accessing RStudio using a web browser. The RStudio IDE is a product of Posit PBC (formerly RStudio PBC, formerly RStudio Inc.). 

### Package: tidyverse

The `tidyverse' is an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures. 

We will mainly focus on some packages in this collections in this limited two hour introduction.

The goal of readr is to provide a fast and friendly way to read rectangular data from delimited files, such as comma-separated values (CSV) and tab-separated values (TSV). It is designed to parse many types of data found in the wild, while providing an informative problem report when parsing leads to unexpected results. If you are new to readr, the best place to start is the data import chapter in R for Data Science.

The readxl package makes it easy to get data out of Excel and into R. Compared to many of the existing packages (e.g. gdata, xlsx, xlsReadWrite) readxl has no external dependencies, so it’s easy to install and use on all operating systems. It is designed to work with tabular data.

ggplot2 is an open-source data visualization package for the statistical programming language R. Created by Hadley Wickham in 2005, ggplot2 is an implementation of Leland Wilkinson's Grammar of Graphics—a general scheme for data visualization which breaks up graphs into semantic components such as scales and layers. ggplot2 can serve as a replacement for the base graphics in R and contains a number of defaults for web and print display of common scales. Since 2005, ggplot2 has grown in use to become one of the most popular R packages.

### Reference and useful links

+ [tidyverse](https://www.tidyverse.org/)

+ [package: readr](https://readr.tidyverse.org/)

+ [package: readxl](https://readxl.tidyverse.org/)

+ [package: ggplot2](https://ggplot2.tidyverse.org/)

+ [r-graph-gallery: ggplot2](https://r-graph-gallery.com/ggplot2-package.html)

+ [ggplot2: Elegant Graphics for Data Analysis (3e)](https://ggplot2-book.org/)

+ [IBM data-visualization](https://www.ibm.com/topics/data-visualization)

+ [Wiki ggplot2](https://en.wikipedia.org/wiki/Ggplot2)
